[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fymoney = "9PbXHvSA4k86YpoJonchC9LHaFNuGv7XiEf8MdD4ZYNp"

[programs.devnet]
fymoney = "9PbXHvSA4k86YpoJonchC9LHaFNuGv7XiEf8MdD4ZYNp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
